### ISSUE TITLE
Consider using marked instead of showdown

### ISSUE THREAD

**Issue by giodamelio** [pioul/Minimalist-Online-Markdown-Editor#8]
I love your editor, I use it to write docs all the time(I even wrote this issue with it). The problem is, it doesn't support [Github flavored markdown](https://help.github.com/articles/github-flavored-markdown). If you used [marked](https://github.com/chjj/marked), you would get GFM for free, on top of that you get a few nice perks.

 - [Marked is considerably faster](http://jsperf.com/markdown-implementations/2). I know that is a simple test, but in projects I have used it in, it has been true across the board.
 - [Super easy code highlighting using you highlighting library of choice](https://github.com/chjj/marked#highlight). This would be great.
 - [Smarter list logic](https://github.com/chjj/marked#smartlists). Original markdown lists can be a bit of a pain, especially when nesting lists.

**Comment by pioul** [comment]
Hey, I'm back to this issue. Other features I'm implementing would greatly benefit from a faster and extendable Markdown converter, so adopting a new one can't wait much more.

@puzrin, I see you're a very active contributor to both [Markdown it!](https://github.com/markdown-it/markdown-it) and [remarkable](https://github.com/jonschlinkert/remarkable), although you seem more active on Markdown it! lately. Which of the two would you advise me to use in MME? It'll run in the browser, and should be production-ready, fast, and extendable. (At first sight they both seem to match these criteria, so I'm interested in knowing which one you think is best by these standards.)

@giodamelio, I'm also interested in your opinion on these two if you've had a look at them.

Marked doesn't seem to be maintained actively anymore, and it looked at most on a par with remarkable and Markdown it!, so let's cross it off the list.

One of the features I'm implementing in the editor and makes me want to have more control over the converter is a better sync-scrolling.

The current sync-scrolling implementation simply proportionately scrolls the Markdown source and preview panels: Markdown on one side, rendered HTML on the other. I've been able to improve this approach by taking care of most edge cases; without going into unnecessary details, it requires adding a caret marker in the rendered HTML so that the area being edited in the document can be made visible at all times.

That works really great, except for one thing: the Markdown converter isn't extendable, hence the caret marker (a `<span>`) has to be added before parsing the Markdown source. As you can guess, that messes with the parser when the caret precedes any block construct. E.g., a header preceded by a caret marker (`<span id="caret-marker-5640668"></span># Header`) is converted to `<p><span id="caret-marker-5640668"></span># Header</p>`. That's what I'm trying to avoid.

Do you know if one of these converters would make solving this issue easy enough? I don't know exactly how they work under the hood, but being able to tell the lexer to completely ignore an arbitrary string of text would likely solve it. (That'd allow the conversion to run as if no caret marker existed in the source, and I'd just replace it with an HTML element in the output HTML.)

**Comment by puzrin** [comment]
@pioul https://github.com/markdown-it/markdown-it#authors use `markdpwn-it`, it's much more fresh.

**Comment by pioul** [comment]
I did scroll down to have a look at the authors, but didn't the line just below. Got it, I'll test drive Markdown it! :-)

Before I start diving into it, since you've wrote so much of it yourself, any idea if hooking into the lexer in the fashion described above is possible?

**Comment by giodamelio** [comment]
markdown-it looks nice.
@pioul I took a quick look at the plugin system, and I think you should be able to use it instead of manually inserting characters.

**Comment by giodamelio** [comment]
You should take a look at the [markdown-it example page](https://markdown-it.github.io/), it has synced scrolling.

**Comment by puzrin** [comment]
I think, it will be more fast to read the docs and see sync scroll implementation in demo. Source mapping for lines already exists.

Demo has sync scroll to one side only because me & Alex don't like browser programming, and had no time to polish :)

**Comment by giodamelio** [comment]
[Just updated the benchmark](http://jsperf.com/showdown-js-vs-marked/6). Seems to run fine in the latest Chrome and Firefox.

**Comment by pioul** [comment]
Yeah, I had a look at it earlier today. Mapping lines is a great approach for precise sync scrolling (which "proportional scrolling" is less good at), and I plan on implementing just that later on, but I'll stay away from that complexity (mirror div and stuff) for now.

Unfortunately, both approaches have the same pitfall: the area being edited isn't always visible in the preview. See below:

![](https://cloud.githubusercontent.com/assets/2307365/5883756/cc911a4e-a355-11e4-9549-a1d49a3c6d62.png)

The only way to solve this is to add a caret marker, which is why I'm more interested in this for the time being. I've inspected the source of the demo more carefully than I did earlier, as well as the docs, and the renderer indeed looks powerful enough for what I want to do; thanks for the pointer.

I'll play around with Markdown it! in the coming days, and will keep you posted here.

**Comment by jarvisniu** [comment]
I can't believe that you really made it. That was awesome!

But it seems still not so precise as @pioul said:

> the area being edited isn't always visible in the preview.

The good news is that I find out the reasons.

There seem to be two reasons:

1. The word wrap of `<textarea>` make the calculated line number a little bigger than the actual.
2. The calculated line height is 18.57 but the actual is 18.

Following these two steps in Chrome Dev Tools will make the sync scrolling very precise:

1. Add a `wrap="off"` attribute to the `<textarea>`.
2. In the source file `index.js` function `syncScroll()` line 238, change `parseFloat` to `parseInt` and save it.

Now when you scroll the editor, the first lines will always be corresponding.

**Comment by puzrin** [comment]
In general, that's an application task, how to do scroll. Demo has simplified logic, because it has another goal - demonstrate mapping feature. I even considered use Ace / CodeMirror to remove lines calculations.

It would be nice, if someone could improve it, because i'm not strong in interfaces programming.

**Comment by jarvisniu** [comment]
Yes, I also think using Ace or CodeMirror will be good. I'll try it.

**Comment by pioul** [comment]
I'm glad to report that as of [v3.1.0](https://github.com/pioul/Minimalist-Online-Markdown-Editor/releases/tag/v3.1.0), MME has ditched Showdown.js in favor of Markdown-it!

@giodamelio, that means the needs you highlighted when you first suggested leaving Showdown.js behind are finally met: a (way) faster converter, better lists through CommonMark support, GFM tables support. I voluntarily left out syntax highlighting in code blocks for now, but that'll come later. Thanks again for the suggestion!

@puzrin, thanks for the great library. I really liked diving into Markdown-it's source and architecture, good stuff. After playing with tokens and parser rules, I've ended up writing a plugin that extends renderer rules to map lines in the preview panel (like in your demo, except MME doesn't have a source mirror div yet). I also have jotted down several small suggestions for Markdown-it, so expect me to open / comment on some issues soon :-)
