### ISSUE TITLE
Tabbing selected text cannot be undone

### ISSUE THREAD

**Issue by janharms** [pioul/Minimalist-Online-Markdown-Editor#9]
When selecting a lot of text (e.g. code) which should be indented pressing the tab-key inserts a tab and removes all selected text. This operation cannot be undone.
Since four empty spaces are the defacto standard to create a code block they should be inserted when a selection larger than one line.

(I am on windows 7 with chrome 38.0.2125.104 m)

(Thank you for your work on this product.)

**Comment by pioul** [comment]
Hey,

I've just published a new version of the editor that implements this feature :-)

Now, when multiple lines are selected and <kbd>TAB</kbd> is pressed, they'll be indented. Press <kbd>SHIFT + TAB</kbd>, and they'll be unindented. Indentation still uses tabs, though. I'll consider adding a switch "indent with spaces/tabs" if that's something you really care about.

Regarding undoing operations, although the text won't be replaced with a tab anymore (which was extremely annoying considering you couldn't undo it, agreed), the indenting operation remains non-undoable. This is due to the way Chrome handles such operations: Firefox behaves differently, and if you open up the [web app](http://markdown.pioul.fr/) there, you'll have a working undo mechanism.

The MME [Chrome app](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf) does, however, implement a custom undo mechanism, which will eventually make its way into the web app.

Cheers!
